Visual Studio Code (1.84.2, undefined, desktop)
Jupyter Extension Version: 2023.10.1100000000.
Python Extension Version: 2023.20.0.
Platform: linux (x64).
Workspace folder ~/Documents/01_UPenn/99_Ref/01_PyDrake, Home = /home/anirudhkailaje
10:46:29.405 [info] Start refreshing Kernel Picker (1700149589405)
10:46:29.407 [info] Using Pylance
10:46:30.421 [info] Start refreshing Interpreter Kernel Picker
10:46:30.456 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher  (Python Path: /bin/python3, Unknown, 3.11.2) for '~/Documents/01_UPenn/99_Ref/01_PyDrake/updating_costs_and_constraints.ipynb' (disableUI=true)
10:46:30.478 [warn] Failed to get activated env vars for /bin/python3 in 958ms
10:46:30.489 [info] Process Execution: /bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
10:46:30.509 [warn] Failed to get activated env vars for /bin/python3 in 44ms
10:46:30.521 [info] Process Execution: /bin/python3 -m pip list
10:46:30.532 [info] Process Execution: /bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
10:46:30.541 [info] Process Execution: /bin/python3 -m ipykernel_launcher --f=~/.local/share/jupyter/runtime/kernel-v2-13305gpzk5PpbYgn9.json
    > cwd: ~/Documents/01_UPenn/99_Ref/01_PyDrake
10:46:30.958 [info] ipykernel version & path 6.17.0, /usr/lib/python3/dist-packages/ipykernel/__init__.py for /bin/python3
10:46:31.632 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
10:46:31.783 [info] End refreshing Kernel Picker (1700149589405)
10:46:31.852 [warn] No interpreter for Pylance for Notebook URI "~/Documents/01_UPenn/99_Ref/01_PyDrake/mathematical_program.ipynb"
10:46:31.869 [warn] StdErr from Kernel Process Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 981, in launch_instance
    app.initialize(argv)
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 666, in initialize
    self.init_sockets()
  File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 307, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 244, in _bind_socket
    return self._try_bind_socket(s, port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 220, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/usr/lib/python3/dist-packages/zmq/sugar/socket.py", line 232, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 568, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
10:46:32.116 [error] [Error: Message Decoding: Incorrect;
Obtained "4536b4f250b4c09ca5b04e56dd72bda63bdc55f14a79a6863c7ca6ec722563ac"
Expected "c00e327401c459498473aeab9961ba6195301b87fc78b509d54d317154cc4f3f"
	at t.Jx (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-linux-x64/out/extension.node.js:2:315668)
	at WebSocket.onIncomingMessage (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-linux-x64/out/extension.node.js:24:105325)
	at WebSocket.processSocketMessages (~/.vscode/extensions/ms-toolsai.jupyter-2023.10.1100000000-linux-x64/out/extension.node.js:24:104669)]
10:46:32.318 [error] Disposing session as kernel process died ExitCode: 1, Reason: zmq.error.ZMQError
10:46:32.319 [info] Dispose Kernel process 13604.
10:46:35.016 [warn] Didn't get response for requestKernelInfo after 3000ms.
11:25:33.119 [info] Disposing HostJupyterExecution
11:25:33.119 [info] Dispose Kernel '~/Documents/01_UPenn/99_Ref/01_PyDrake/updating_costs_and_constraints.ipynb' associated with '~/Documents/01_UPenn/99_Ref/01_PyDrake/updating_costs_and_constraints.ipynb'
11:25:33.120 [info] Disposing HostJupyterExecution
11:25:33.121 [info] Dispose Kernel '~/Documents/01_UPenn/99_Ref/01_PyDrake/updating_costs_and_constraints.ipynb' associated with '~/Documents/01_UPenn/99_Ref/01_PyDrake/updating_costs_and_constraints.ipynb'
